### ISSUE TITLE
 extension doesnot work

### ISSUE THREAD

**Issue by sherry085** [hallatore/stable-diffusion-webui-chatgpt-utilities#5]
Hi，
Thanks for ur great work, when I use this extension ,i meet the following question:
I cloned this project to the webui/extensions and I can see this extension in  installed column，but I cannot find it in Function bar

![image](https://user-images.githubusercontent.com/52395960/226615385-8f4b569f-573d-4697-9482-cdf74549913d.png)

**Comment by luochenxi** [comment]
I have encountered the same problem, how did you solve it? @sherry085

**Comment by hallatore** [comment]
@luochenxi It shows up under "scripts" for txt2img and img2img tabs.

**Comment by luochenxi** [comment]
@sherry085 thx
