### ISSUE TITLE
How to do a large amount of generation?

### ISSUE THREAD

**Issue by aetherwu** [hallatore/stable-diffusion-webui-chatgpt-utilities#9]
I've tried batch count but it only repeat one prompt for multiple times. 
What is I would like to generate 200+ different photos automatically?

**Comment by hallatore** [comment]
It sometimes fails since the batch count is part of the prompt. I usually make it generate 6 or 8 versions, and just right click Generate and select "run forever".

**Comment by aetherwu** [comment]
> It sometimes fails since the batch count is part of the prompt. I usually make it generate 6 or 8 versions, and just right click Generate and select "run forever".

But it could be to many for an overnight running...
